FROM python:3.12-slim

# Install system dependencies
RUN apt-get update && \
    apt-get install chromium-driver -y
# Set working directory
WORKDIR /app

# Copy and install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your code
COPY . .

# Command to run your Flask app
CMD ["python", "run.py"]
